# Generated by Django 3.1.2 on 2021-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCloudChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.IntegerField(default=0, verbose_name='帧点云编号')),
                ('cloud_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='帧点云名称')),
                ('cloud_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='帧点云url')),
                ('cloud_project', models.CharField(blank=True, max_length=100, null=True, verbose_name='帧点云所属用户')),
            ],
            options={
                'verbose_name': '帧点云',
                'verbose_name_plural': '帧点云',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='轨迹属于点云')),
                ('cloud_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='轨迹数据')),
                ('cloud_project', models.CharField(blank=True, max_length=100, null=True, verbose_name='轨迹属于项目')),
            ],
            options={
                'verbose_name': '点云轨迹',
                'verbose_name_plural': '点云轨迹',
            },
        ),
    ]
