# Generated by Django 3.1.2 on 2021-05-27 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0003_circlepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目编号')),
                ('project_name', models.CharField(blank=True, default='项目', max_length=32, null=True, verbose_name='项目名称2')),
                ('tile_name', models.CharField(blank=True, default='tile', max_length=32, null=True, verbose_name='点云瓦片名称')),
                ('active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('status', models.CharField(default='notStart', max_length=32, verbose_name='扫描状态')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '扫描项目',
                'verbose_name_plural': '扫描项目',
            },
        ),
        migrations.AddField(
            model_name='pointcloudchunk',
            name='project_id',
            field=models.IntegerField(default=0, verbose_name='项目id'),
        ),
    ]
