# Generated by Django 3.1.2 on 2021-05-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0003_circlepoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CirclePoint',
        ),
    ]
