# Generated by Django 3.2.3 on 2021-06-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0004_auto_20210527_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlepoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='circlepoint',
            name='circle_point_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='回环点id'),
        ),
    ]
