# Generated by Django 3.1.2 on 2021-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0005_circlepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlepoint',
            name='circle_point_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='结束回环点'),
        ),
        migrations.AlterField(
            model_name='circlepoint',
            name='circle_point_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='开始回环点'),
        ),
    ]
