# Generated by Django 3.1.2 on 2021-05-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0009_auto_20210507_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlepoint',
            name='circle_point_end',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='结束回环点'),
        ),
        migrations.AlterField(
            model_name='circlepoint',
            name='circle_point_start',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='开始回环点'),
        ),
    ]
