# Generated by Django 3.1.2 on 2021-05-24 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0010_auto_20210507_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='项目编号')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='项目名称2')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
        ),
        migrations.AddField(
            model_name='pointcloudchunk',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_id', to='pointCloud.project', verbose_name='所属项目'),
        ),
    ]
