# Generated by Django 3.1.2 on 2021-05-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0012_auto_20210524_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='项目', max_length=32, null=True, verbose_name='项目名称2'),
        ),
    ]
