# Generated by Django 3.1.2 on 2021-05-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0013_auto_20210524_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointcloudchunk',
            name='project_id',
            field=models.IntegerField(default=0, verbose_name='项目id'),
        ),
    ]
