# Generated by Django 3.1.2 on 2021-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0014_auto_20210524_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='tile_name',
            field=models.CharField(blank=True, default='项目', max_length=32, null=True, verbose_name='点云瓦片名称'),
        ),
    ]
