# Generated by Django 3.1.2 on 2021-05-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0015_auto_20210524_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tile_name',
            field=models.CharField(blank=True, default='tile', max_length=32, null=True, verbose_name='点云瓦片名称'),
        ),
    ]
