# Generated by Django 3.1.2 on 2021-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0016_auto_20210524_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='notStart', max_length=32, verbose_name='扫描状态'),
        ),
    ]
