# Generated by Django 3.1.2 on 2021-06-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0017_project_status'),
        ('pointCloud', '0005_auto_20210601_1210'),
    ]

    operations = [
    ]
