# Generated by Django 3.1.2 on 2021-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0020_get_project_data_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
