# Generated by Django 3.1.2 on 2021-06-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0021_auto_20210608_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
