# Generated by Django 3.1.2 on 2021-06-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0022_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='get_project_data',
        ),
    ]
