# Generated by Django 3.1.2 on 2021-06-10 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0023_delete_get_project_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='扫描项目')),
                ('corner_map', models.CharField(blank=True, max_length=80, null=True, verbose_name='corner map url')),
                ('global_cloud_all', models.CharField(blank=True, max_length=80, null=True, verbose_name='global cloud all url')),
                ('global_map', models.CharField(blank=True, max_length=80, null=True, verbose_name='global map url')),
                ('transformations', models.CharField(blank=True, max_length=80, null=True, verbose_name='transformations url')),
                ('tile_item', models.CharField(blank=True, max_length=80, null=True, verbose_name='tile item url')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '扫描数据',
                'verbose_name_plural': '扫描数据',
                'db_table': 'tb_scan_project',
            },
        ),
    ]
