# Generated by Django 3.1.2 on 2021-07-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointCloud', '0024_scanproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CirclePoint',
        ),
        migrations.DeleteModel(
            name='PointCloudChunk',
        ),
        migrations.DeleteModel(
            name='ScanProject',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
