# Generated by Django 3.1.2 on 2021-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pointCloud', '0025_auto_20210706_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_record', models.BooleanField(default=False, verbose_name='是否录制')),
            ],
            options={
                'verbose_name': '扫描配置',
                'verbose_name_plural': '扫描配置',
                'db_table': 'tb_config',
            },
        ),
    ]
